# https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a

# Prevent codecov from commenting
comment: false

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        target: 95%
        branches:
          - master

    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        # in the github diff if they install the codecov browser
        # extension:
        # https://github.com/codecov/browser-extension
        target: 95%

ignore:
- "**/setup.py"
- "*/pmdarima/__check_build/*"
- "*/pmdarima/_build_utils/*"
- "*/pmdarima/_config.py"
- "*/pmdarima/__init__.py"
- "*/pmdarima/compat/matplotlib.py"
- "*/pmdarima/utils/tests/test_vis.py"
- "*/pmdarima/utils/visualization.py"
