# Prevent codecov from commenting
comment: false

# Opts scikit uses
coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%

    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        # in the github diff if they install the codecov browser
        # extension:
        # https://github.com/codecov/browser-extension
        target: auto
        threshold: 1%

ignore:
- "**/setup.py"
- "*/pmdarima/__check_build/*"
- "*/pmdarima/_build_utils/*"
- "*/pmdarima/_config.py"
- "*/pmdarima/__init__.py"
- "*/pmdarima/compat/matplotlib.py"
- "*/pmdarima/utils/tests/test_vis.py"
- "*/pmdarima/utils/visualization.py"
