# The Travis build will test both Linux AND OSX distributions, but language needs to be
# overridden to "generic" for Mac, otherwise the build will fail until Python is downloaded
# via Homebrew (which is handled in the before_install.sh). Note that none of the test envs
# or wheels test/create artifacts on <64 bit Linux or Mac. All artifacts are 64-bit ONLY.
language: python
sudo: required

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

before_install: source build_tools/travis/before_install.sh
env:
  global:
    - PYMODULE=pyramid
    - TEST_DIR=/tmp/pyramid
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"
    - TWINE_USERNAME="tgsmith61591.gh"
    - TWINE_PASSWORD:
      - secure: "zkaE+qqr0oghwNqsz5g99kVr3nVYCSxlzyWlpWudJfuiCFm3RRdh+Gc89V2ZiXNqsMKtDxpELPbY3R0gjj4m/N963m/XAtIQmm+ivWayL577+AaScFSnGXu9IJdRvIo27D/F5FEqzPHGFtQRv5AJYNjNPQoBPuVNwer4N89s6WjZ5yrDhBip13umLDEJvY6TSUaKY2fZFogmkMGZBjQd87dCQ7mf3Y77NJ8grLvZwbpUWQJLIFcGQqlQCSCBBYM4tPebpA2j9uDOvZdJ4aBqs/qkGazjLco3yy6kbFV/21V0TxUzHx7DvmD4VdKR/eCCMOfxWAuXoDNRYmgsubb9EcanY4HTYUz/NOvDTEte6UEta8UN92glGrDYf2f+Cf0YKKVQlL+kGQdDAXRamqGVrmJTWbR3CYAb9bYcN/86INSwqto65aQKlslV5Skd8v4UqD2ZRZCz5shVbkpKMXNFG/mEnTf/EJ60OlnRiIDiwfKPMlFEfQSpoJZEf4b1gk79VtMV2shM8IMM67bbJ1lxV/eqzHCJaWU6waoAkYSrI7aGPF3BReCUOzoeuqHF6ZhjuSQqdgUywVxYNPwbSFxX8x8D9evKc3GI2eUDM6+3ZkdLlOLY2V/RrocpPDTx9Bn/u50OW4pr0FfCGLWU7F1xnCiZrUw8K5ddywzhUx3xCPo="

matrix:
  include:
    # This environment tests the oldest supported anaconda env. Except some of these (i.e., statsmodels
    # and sklearn) require higher versions of numpy, so cannot really test *actual* oldest... this also
    # tests against linux.
    - os: linux
      dist: trusty
      services:
        - docker
      env: DISTRIB="conda" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.5"
           COVERAGE=true SCIKIT_LEARN_VERSION="0.17.1" DEPLOY=true CACHEC=true
           DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64" DOCKER_CONTAINER_NAME="pyramidcontainer"

    # This environment tests the same conditions as above, but tests against MAC OS X,
    # using virtualenv instead of the conda python distribution
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.5"
           COVERAGE=true SCIKIT_LEARN_VERSION="0.17.1" DEPLOY=true CACHEC=false

    # This environment tests Python 3.5 support on linux
    - os: linux
      dist: trusty
      services:
        - docker
      env: DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.25.2"
           COVERAGE=true SCIKIT_LEARN_VERSION="0.18" STATSMODELS_VERSION="0.8"
           DEPLOY=true CACHEC=true DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
           DOCKER_CONTAINER_NAME="pyramidcontainer"

    # This environment tests Python 3.5 support on MAC OS X, using virtualenv
    # instead of the conda python distribution
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.25.2"
           COVERAGE=true SCIKIT_LEARN_VERSION="0.18" STATSMODELS_VERSION="0.8"
           DEPLOY=true CACHEC=false

    # This environment tests the newest supported Anaconda release (4.4.0) and
    # runs on linux
    - os: linux
      dist: trusty
      env: DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.25.2"
           COVERAGE=true SCIKIT_LEARN_VERSION="0.18" STATSMODELS_VERSION="0.8"
           DEPLOY=false CACHEC=true

    # This environment use pytest to run the tests. It uses the newest
    # supported Anaconda release (4.4.0) and tests with pytests instead of nosetests.
    # This test runs on linux.
    - os: linux
      dist: trusty
      env: USE_PYTEST="true" DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
           NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.25.2"
           COVERAGE=false SCIKIT_LEARN_VERSION="0.18" STATSMODELS_VERSION="0.8"
           DEPLOY=false CACHEC=true

install: source build_tools/travis/install.sh
before_script: bash build_tools/travis/before_script.sh
script: bash build_tools/travis/test_script.sh
after_success:
  - source build_tools/travis/after_success.sh
  # Build the wheels every time so we can debug
  - bash build_tools/travis/build_wheels.sh
  - ls -la dist/

notifications:
  slack:
    rooms:
    - tgsmith61591-gh:mWyfLXzxRAHCKD2QRHWvHZaX#pyramid-cicd
    on_success: always
    on_failure: always
    on_pull_requests: true

deploy:
  provider: script
  skip_cleanup: true
  #on:
  #  tags: true # Upload on tagged releases
  #  condition: "$DEPLOY = true"
  on:
    branch: develop
  script:
    - python -m twine upload --skip-existing dist/*
