# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This .yml file is based on scikit-learn's Appveyor CI setup, adapted for use with Pyramid
# https://ci.appveyor.com/project/tgsmith61591/pyramid

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build_tools\\appveyor\\run_with_env.cmd"
    #WHEELHOUSE_UPLOADER_USERNAME: sklearn-appveyor
    #WHEELHOUSE_UPLOADER_SECRET:
    #  secure: BQm8KfEj6v2Y+dQxb2syQvTFxDnHXvaNktkLcYSq7jfbTOO6eH9n09tfQzFUVcWZ

  matrix:
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"

    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"

    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"

    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - ps: conda install numpy scipy cython scikit-learn statsmodels pip nose patsy --quiet
  - python setup.py develop

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - "mkdir empty_folder"
  - "cd empty_folder"
  - nosetests --exe -v -A "not slow" pyramid

  # Move back to the project folder
  - "cd .."

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

# cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth
  # usage on our rackspace account.
  # - '%APPDATA%\pip\Cache'

notifications:
  - provider: Slack
    auth_token:
      secure: mWyfLXzxRAHCKD2QRHWvHZaX
    channel: 'tgsmith61591-gh#pyramid-cicd'
