version: 2

jobs:
  # For testing PyPy rather than CPython
  pypy36:
    docker:
      - image: pypy:3-6.0.0
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - pypy3-ccache-{{ .Branch }}
          # fallback to using the latest cache if no exact match is found
          - pypy3-ccache

      - checkout
      - run: ./build_tools/circle/build_test_pypy.sh
      - save_cache:
          key: pypy3-ccache-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - ~/.ccache
            - ~/.cache/pip

  # For testing lint
  test-linting:
    docker:
      - image: python:3.6
    working_directory: ~/pyramid
    steps:
    - checkout
    - run: make test-lint

  # For building and deploying documentation
  # documentation:

workflows:
  version: 2

  # All PyPy jobs:
  pypy:
    jobs:
      - pypy36
      - test-linting
