name: Update Downloads Badges

on:
  schedule:
    - cron: '15 19 * * *'  # Every day at 7:15pm UTC -> 1:15pm CST or 2:15pm CDT

jobs:
  update:
    name: Update Downloads Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Run Python Script
        run: python etc/downloads_badges.py
        env:
          ZAPIER_SHA: ${{ secrets.ZAPIER_SHA }}